### ISSUE TITLE
Error in windows writing to logs

### ISSUE THREAD

**Issue by chrisparnin** [alt-code/TaskLights#9]
Have to remove logs/ directory each time, otherwise will get the following error:
```
The system cannot find the file specified.
Error: Command failed: copy /Y heatmap_template* logs &amp;&amp; cd logs &amp;&amp; move /Y gitignore .gitignore &amp;&amp; npm install &amp;&amp; grunt mustache_render &amp;&amp; grunt gh-pages &amp;&amp; git pull
The system cannot find the file specified.

    at checkExecSyncError (child_process.js:464:13)
    at Object.execSync (child_process.js:504:13)
    at Object.&lt;anonymous&gt; (C:\projects\TaskLights\src\blink.js:228:30)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
closing
```

**Comment by ssmirr** [comment]
I could reproduce the error. It seems it cannot find the `grunt-cli` that's installed locally on Windows. You need to install `grunt-cli` globally to make this work...
``` bash
npm install -g grunt-cli
```

**Comment by chrisparnin** [comment]
That does not seem like an appropriate fix.

It should just use the local grunt which is located here:
`node_modules\.bin\grunt`
